# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.10.3
  - 2.10.2
  - 2.10.1
  - 2.9.3
  - 2.9.2
  - 2.9.1
# Branches to test
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - ross@10gen.com
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
services:
  - mongodb