baseurl = "/casbah/2.8"
languageCode = "en-us"
title = "Casbah"
theme = "mongodb"
canonifyurls = false

[blackfriday]
  plainIdAnchors = true

# Update versions in mongodb.toml as well
[[menu.main]]
    name = "API Documentation"
    pre = "<i class='fa fa-file-text-o'></i>"
    weight = 90
    identifier = "apiDocs"
    url = "/scaladoc"

[[menu.main]]
    name = "Source Code"
    pre = "<i class='fa fa-github'></i>"
    weight = 90
    identifier = "githubLink"
    url = "https://github.com/mongodb/casbah"
